import type { ModelCapabilities } from "./types"

/**
 * Canonical model capabilities — intrinsic properties that don't vary across providers.
 * Pricing, caching, and other provider-specific config lives in each provider's model registry.
 */
export const MODEL_CAPABILITIES: Record<string, ModelCapabilities> = {
    "claude-haiku-4-5-20251001": {
        maxTokens: 64_000,
        contextWindow: 200_000,
        supportsImages: true,
        supportsReasoning: true,
    },
    "claude-opus-4-6": {
        maxTokens: 128_000,
        contextWindow: 200_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "claude-opus-4-6:1m": {
        maxTokens: 128_000,
        contextWindow: 1_000_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "claude-opus-4-7:1m": {
        maxTokens: 128_000,
        contextWindow: 1_000_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "claude-opus-4-7:fast": {
        maxTokens: 128_000,
        contextWindow: 200_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "claude-opus-4-7": {
        maxTokens: 128_000,
        contextWindow: 200_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "claude-opus-4-8": {
        maxTokens: 128_000,
        contextWindow: 200_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "claude-opus-4-8:1m": {
        maxTokens: 128_000,
        contextWindow: 1_000_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "claude-opus-4-8:fast": {
        maxTokens: 128_000,
        contextWindow: 200_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "claude-opus-4-8:1m:fast": {
        maxTokens: 128_000,
        contextWindow: 1_000_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "claude-fable-5": {
        maxTokens: 128_000,
        contextWindow: 200_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "claude-sonnet-4-20250514:1m": {
        maxTokens: 64_000,
        contextWindow: 1_000_000,
        supportsImages: true,
        supportsReasoning: true,
    },
    "claude-sonnet-4-5-20250929:1m": {
        maxTokens: 64_000,
        contextWindow: 1_000_000,
        supportsImages: true,
        supportsReasoning: true,
    },
    "claude-sonnet-4-6": {
        maxTokens: 64_000,
        contextWindow: 200_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "claude-sonnet-4-6:1m": {
        maxTokens: 64_000,
        contextWindow: 1_000_000,
        supportsImages: true,
        supportsReasoning: true,
        supportsAdaptiveThinking: true,
    },
    "codestral-2501": {
        maxTokens: 256_000,
        contextWindow: 256_000,
        supportsImages: false,
    },
    "DeepSeek-R1": {
        maxTokens: 8192,
        contextWindow: 64_000,
        supportsImages: false,
    },
    "DeepSeek-R1-0528": {
        maxTokens: 7168,
        contextWindow: 131072,
        supportsImages: false,
    },
    "deepseek-r1-250120": {
        maxTokens: 32_768,
        contextWindow: 64_000,
        supportsImages: false,
    },
    "DeepSeek-R1-Distill-Llama-70B": {
        maxTokens: 4096,
        contextWindow: 131072,
        supportsImages: false,
    },
    "DeepSeek-V3": {
        maxTokens: 16_384,
        contextWindow: 64_000,
        supportsImages: false,
    },
    "DeepSeek-V3-0324": {
        maxTokens: 7168,
        contextWindow: 131072,
        supportsImages: false,
    },
    "deepseek-v3-250324": {
        maxTokens: 12_288,
        contextWindow: 128_000,
        supportsImages: false,
    },
    "DeepSeek-V3.1": {
        maxTokens: 7168,
        contextWindow: 131072,
        supportsImages: false,
    },
    "DeepSeek-V3.1-Terminus": {
        maxTokens: 7168,
        contextWindow: 131072,
        supportsImages: false,
    },
    "DeepSeek-V3.2": {
        maxTokens: 131_072,
        contextWindow: 163_840,
        supportsImages: false,
        supportsReasoning: true,
    },
    "doubao-1-5-pro-256k-250115": {
        maxTokens: 12_288,
        contextWindow: 256_000,
        supportsImages: false,
    },
    "doubao-1-5-pro-32k-250115": {
        maxTokens: 12_288,
        contextWindow: 32_000,
        supportsImages: false,
    },
    "gemini-2.0-flash-thinking-exp-01-21": {
        maxTokens: 65_536,
        contextWindow: 1_048_576,
        supportsImages: true,
    },
    "gemini-2.5-flash": {
        maxTokens: 65536,
        contextWindow: 1_048_576,
        supportsImages: true,
        thinkingConfig: {
            maxBudget: 24576,
        },
    },
    "gemini-2.5-flash-lite-preview-06-17": {
        maxTokens: 64000,
        contextWindow: 1_000_000,
        supportsImages: true,
        thinkingConfig: {
            maxBudget: 24576,
        },
    },
    "gemini-2.5-pro": {
        maxTokens: 65536,
        contextWindow: 1_048_576,
        supportsImages: true,
        thinkingConfig: {
            maxBudget: 32767,
        },
    },
    "gemini-2.5-pro-exp-03-25": {
        maxTokens: 65536,
        contextWindow: 1_048_576,
        supportsImages: true,
    },
    "gemini-3-flash-preview": {
        maxTokens: 65536,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsReasoning: true,
        thinkingConfig: {
            geminiThinkingLevel: "high",
            supportsThinkingLevel: true,
        },
    },
    "gemini-3-pro-preview": {
        maxTokens: 8192,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsReasoning: true,
        thinkingConfig: {
            geminiThinkingLevel: "high",
            supportsThinkingLevel: true,
        },
    },
    "gemini-3.1-pro-preview": {
        maxTokens: 8192,
        contextWindow: 1_048_576,
        supportsImages: true,
        supportsReasoning: true,
        thinkingConfig: {
            geminiThinkingLevel: "high",
            supportsThinkingLevel: true,
        },
    },
    "glm-4.6": {
        supportsTools: true,
        maxTokens: 200_000,
        contextWindow: 200_000,
        supportsImages: false,
        supportsReasoning: true,
    },
    "glm-5": {
        supportsTools: true,
        maxTokens: 8_192,
        contextWindow: 200_000,
        supportsImages: false,
    },
    "glm-5.1": {
        supportsTools: true,
        maxTokens: 128_000,
        contextWindow: 200_000,
        supportsImages: false,
        supportsReasoning: true,
        thinkingConfig: {
            maxBudget: 128_000,
        },
    },
    "gpt-5.4": {
        name: "GPT-5.4",
        maxTokens: 128_000,
        contextWindow: 1_000_000,
        supportsImages: true,
        supportsReasoning: true,
    },
    "gpt-5.4-mini": {
        name: "GPT-5.4 mini",
        maxTokens: 128_000,
        contextWindow: 400_000,
        supportsImages: true,
        supportsReasoning: true,
    },
    "gpt-5.4-nano": {
        name: "GPT-5.4 nano",
        maxTokens: 128_000,
        contextWindow: 400_000,
        supportsImages: true,
        supportsReasoning: true,
    },
    "gpt-5.4-pro": {
        name: "GPT-5.4 Pro",
        maxTokens: 128_000,
        contextWindow: 1_050_000,
        supportsImages: true,
        supportsReasoning: true,
    },
    "gpt-5.5": {
        name: "GPT-5.5",
        maxTokens: 128_000,
        contextWindow: 1_000_000,
        supportsImages: true,
        supportsReasoning: true,
    },
    "gpt-oss-120b": {
        maxTokens: 8192,
        contextWindow: 128_000,
        supportsImages: false,
    },
    "gpt-oss-20b": {
        maxTokens: 8192,
        contextWindow: 128_000,
        supportsImages: false,
    },
    "grok-4-1-fast-non-reasoning": {
        contextWindow: 2_000_000,
        supportsImages: true,
    },
    "grok-4-1-fast-reasoning": {
        contextWindow: 2_000_000,
        supportsImages: false,
    },
    "grok-code-fast-1": {
        contextWindow: 256_000,
        supportsImages: false,
    },
    "Hermes-4-405B": {
        maxTokens: 8192,
        contextWindow: 128_000,
        supportsImages: false,
    },
    "Hermes-4-70B": {
        maxTokens: 8192,
        contextWindow: 128_000,
        supportsImages: false,
    },
    "kimi-k2-0905-preview": {
        maxTokens: 16384,
        contextWindow: 262144,
        supportsImages: false,
        supportsReasoning: true,
        supportsTools: true,
    },
    "kimi-k2-thinking": {
        supportsTools: true,
        maxTokens: 163_800,
        contextWindow: 262_000,
        supportsImages: false,
        supportsReasoning: true,
    },
    "kimi-k2-thinking-turbo": {
        maxTokens: 32_000,
        contextWindow: 262_144,
        supportsImages: false,
        supportsReasoning: true,
        supportsTools: true,
    },
    "kimi-k2.5": {
        maxTokens: 32_000,
        contextWindow: 262_144,
        supportsImages: true,
        supportsReasoning: true,
        supportsTools: true,
    },
    "kimi-k2.6": {
        maxTokens: 32_000,
        contextWindow: 262_144,
        supportsImages: true,
        supportsReasoning: true,
        supportsTools: true,
    },
    "llama-4-maverick-17b-128e-instruct": {
        maxTokens: 4096,
        contextWindow: 131072,
        supportsImages: true,
    },
    "llama-4-maverick-17b-128e-instruct-maas": {
        maxTokens: 128_000,
        contextWindow: 1_048_576,
        supportsImages: true,
    },
    "llama-4-scout-17b-16e-instruct-maas": {
        maxTokens: 1_000_000,
        contextWindow: 10_485_760,
        supportsImages: true,
    },
    "Meta-Llama-3.1-8B-Instruct": {
        maxTokens: 4096,
        contextWindow: 16384,
        supportsImages: false,
    },
    "Meta-Llama-3.3-70B-Instruct": {
        maxTokens: 3072,
        contextWindow: 131072,
        supportsImages: false,
    },
    "MiniMax-M2.7": {
        supportsTools: true,
        maxTokens: 128_000,
        contextWindow: 192_000,
        supportsImages: false,
        supportsReasoning: true,
    },
    "MiniMax-M2.7-highspeed": {
        supportsTools: true,
        maxTokens: 128_000,
        contextWindow: 192_000,
        supportsImages: false,
        supportsReasoning: true,
    },
    "MiniMax-M3": {
        supportsTools: true,
        maxTokens: 128_000,
        contextWindow: 1_000_000,
        supportsImages: false,
        supportsReasoning: true,
    },
    "mistral-small-2503": {
        maxTokens: 128_000,
        contextWindow: 128_000,
        supportsImages: true,
    },
    "moonshotai/Kimi-K2-Instruct": {
        supportsTools: true,
        maxTokens: 131_072,
        contextWindow: 131_072,
        supportsImages: false,
    },
    "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8": {
        maxTokens: 8_192,
        contextWindow: 262_000,
        supportsImages: false,
    },
    "qwen-max-latest": {
        maxTokens: 30_720,
        contextWindow: 32_768,
        supportsImages: false,
    },
    "qwen-plus-latest": {
        maxTokens: 16_384,
        contextWindow: 131_072,
        supportsImages: false,
        thinkingConfig: {
            maxBudget: 38_912,
        },
    },
    "qwen-turbo-latest": {
        maxTokens: 16_384,
        contextWindow: 1_000_000,
        supportsImages: false,
        thinkingConfig: {
            maxBudget: 38_912,
        },
    },
    "Qwen3-235B": {
        maxTokens: 4096,
        contextWindow: 65536,
        supportsImages: false,
    },
    "Qwen3-32B": {
        maxTokens: 4096,
        contextWindow: 32768,
        supportsImages: false,
    },
    "qwen3-coder-flash": {
        maxTokens: 65_536,
        contextWindow: 1_000_000,
        supportsImages: false,
    },
    "qwen3-coder-plus": {
        maxTokens: 65_536,
        contextWindow: 1_000_000,
        supportsImages: false,
    },
    "zai-glm-4.7": {
        supportsTools: true,
        maxTokens: 40000,
        contextWindow: 131072,
        supportsImages: false,
    },
}
