// Central registry of well-known file and directory names used across disk storage.
export const GlobalFileNames = {
	apiConversationHistory: "api_conversation_history.json",
	contextHistory: "context_history.json",
	uiMessages: "ui_messages.json",
	diracRecommendedModels: "dirac_recommended_models.json",
	diracModels: "dirac_models.json",
	openRouterModels: "openrouter_models.json",
	vercelAiGatewayModels: "vercel_ai_gateway_models.json",
	groqModels: "groq_models.json",
	basetenModels: "baseten_models.json",
	diracRules: ".diracrules",
	workflows: ".diracrules/workflows",
	hooksDir: ".diracrules/hooks",
	diracruleSkillsDir: ".diracrules/skills",
	diracSkillsDir: ".dirac/skills",
	claudeSkillsDir: ".claude/skills",
	agentsSkillsDir: ".agents/skills",
	aiSkillsDir: ".ai/skills",
	cursorRulesDir: ".cursor/rules",
	cursorRulesFile: ".cursorrules",
	windsurfRules: ".windsurfrules",
	agentsRulesFile: "AGENTS.md",
	taskMetadata: "task_metadata.json",
	remoteConfig: (orgId: string) => `remote_config_${orgId}.json`,
} as const
