import * as fs from "fs"
import * as path from "path"

const MODULES_DIR = path.resolve(__dirname, "../src/core/task/tools/modules")
const OUTPUT_FILE = path.resolve(__dirname, "../src/core/task/tools/discovery/builtin-tools.ts")

const entries = fs
	.readdirSync(MODULES_DIR, { withFileTypes: true })
	.filter((e) => e.isDirectory() && !e.name.startsWith("_"))
	.map((e) => e.name)
	.sort()

const lines = [
	"// AUTO-GENERATED by scripts/generate-tool-barrel.ts",
	"// DO NOT EDIT MANUALLY - regenerate with: npm run generate:tools",
	"",
	...entries.map((name) => `export * as ${name} from "../modules/${name}/tool"`),
	"",
]

fs.writeFileSync(OUTPUT_FILE, lines.join("\n"))
console.log(`Generated barrel with ${entries.length} tool modules.`)
